var activeUsers = [];
var names = [];
names.push("Syed Mohd Azam");
names.push("Syed Hasan Uddin");
names.push("Syed Aqib Uddin");
var ages = [];
ages.push(23);
ages.push(56);
ages.push(79);
ages.push(147);
console.log(activeUsers);
console.log(names);
console.log(ages);
// Another syntax for arrays
var numberedValues = [];
numberedValues.push(197);
numberedValues.push(207);
var pointTypeValues = [];
pointTypeValues.push({ x: 78, y: 89 });
pointTypeValues.push({ x: 87, y: 98 });
console.group(pointTypeValues);
